## These functions create a special object that contains a matrix
## and its inverse

## makeCacheMatrix takes a matrix and returns a list containing
## 1. The matrix
## 2. The inverse of the matrix
## 3. A function to set the inverse
## 4. A function to retrieve the inverse

makeCacheMatrix <- function(x = matrix()) {
    inverse <<- NULL
    set <- function(y) {
        x <<- y
        inverse <<- NULL
    }
    get <- function() x
    setInverse <- function(solve) inverse <<- solve
    getInverse <- function() inverse
    list(set = set, get = get, 
         setInverse = setInverse, 
         getInverse = getInverse)
}


## cacheSolve takes an object generated by makeCacheMatrix and
## 1. Checks if the inverse is already cached
## 2. Generates the inverse if the cache is empty

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
    inverse <- x$getInverse()
    data <- x$get()
    
    
    if(!is.null(inverse)) {
        message("getting cached data")
        return(inverse)
    }
    inverse <- solve(data)
    x$setInverse(inverse)
    inverse
}
